repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-simplify
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
  - id: mypy
    exclude: ^docs/conf.py
    additional_dependencies:
    - types-dataclasses >= 0.1.3
    - types-PyYAML
    - tomli >= 0.2.6, < 2.0.0
    - types-typed-ast >= 1.4.1
    - click >= 8.1.0
    - platformdirs >= 2.1.0
